version: "3"

services:
  server:
    image: nextcloud
    ports:
      - 8080:80
    volumes:
      - ./data/data:/var/www/html/data
      - ./data/config:/var/www/html/config
      - ./data/custom_apps:/var/www/html/custom_apps
  
  maria:
    image: mariadb
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - app.env

    