version: "3.3"

services:

  server:
    image: nextcloud
    restart: always
    ports:
      - 3000:80
    env_file:
      - .env
    volumes:
      - ./data/nc/data:/var/www/html/data
      - ./data/nc/config:/var/www/html/config
      - ./data/nc/custom_apps:/var/www/html/custom_apps
      - ./data/nc/themes:/var/www/html/themes

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data